name: freeflow
description: A TikTok client built for Nostr

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  ndk: ^0.2.5
  go_router: ^14.6.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family:  TikTokIcons
      fonts:
       - asset: assets/fonts/TikTokIcons.ttf

