name: freeflow
description: A TikTok client built for Nostr

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  ndk: ^0.2.5
  go_router: ^14.6.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/svg/"
    - "assets/logo_512.jpg"

